@ECHO OFF
SET BIN=..\..\bin
SET SRC=..\ovllib

REM Compile C sources to ASM
COPY %SRC%\OVLLIB.H OVLLIB.H
copy %SRC%\OVLCOPY.ASM OVLCOPY.ASM
copy %SRC%\OVLGETCS.ASM OVLGETCS.ASM
%BIN%\CC %SRC%\OVLMGR.C >OVLMGR.ASM -a -p -w
%BIN%\CC %SRC%\OVLINIT.C >OVLINIT.ASM -a -p -w
%BIN%\CC %SRC%\OVLLOAD.C >OVLLOAD.ASM -a -p -w
%BIN%\CC %SRC%\OVLCHK.C >OVLCHK.ASM -a -p -w
