SET BIN=..\..\bin

%BIN%\asm ADD32.ASM /p
%BIN%\asm ADD64.ASM /p
%BIN%\asm AND32.ASM /p
%BIN%\asm ATOFT.ASM /p
%BIN%\asm ATOLB.ASM /p
%BIN%\asm ATOP.ASM /p
%BIN%\asm CMP32.ASM /p
%BIN%\asm CMP64.ASM /p
%BIN%\asm CPL32.ASM /p
%BIN%\asm DIV32.ASM /p
%BIN%\asm EQ32.ASM /p
%BIN%\asm EXTEND.ASM /p
%BIN%\asm FILE.ASM /p
%BIN%\asm FT2D.ASM /p
%BIN%\asm FT2S.ASM /p
%BIN%\asm FTADD.ASM /p
%BIN%\asm FTNORMAL.ASM /p
%BIN%\asm FTSUB.ASM /p
%BIN%\asm GE32.ASM /p
%BIN%\asm GT32.ASM /p
%BIN%\asm INC32.ASM /p
%BIN%\asm INT.ASM /p
%BIN%\asm ITOFT.ASM /p
%BIN%\asm LE32.ASM /p
%BIN%\asm LNEG32.ASM /p
%BIN%\asm LSH32.ASM /p
%BIN%\asm LSH64.ASM /p
%BIN%\asm LT32.ASM /p
%BIN%\asm LTOX.ASM /p
%BIN%\asm MESS.ASM /p
%BIN%\asm MIT.ASM /p
%BIN%\asm MOD32.ASM /p
%BIN%\asm MOV32.ASM /p
%BIN%\asm MOV80.ASM /p
%BIN%\asm MUL32.ASM /p
%BIN%\asm NE32.ASM /p
%BIN%\asm NEG32.ASM /p
%BIN%\asm OR32.ASM /p
%BIN%\asm PUTOBJ.ASM /p
%BIN%\asm REQ.ASM /p
%BIN%\asm RSH32.ASM /p
%BIN%\asm RSH64.ASM /p
%BIN%\asm SCAN.ASM /p
%BIN%\asm SUB32.ASM /p
%BIN%\asm SUB64.ASM /p
%BIN%\asm WAITING.ASM /p
%BIN%\asm XOR32.ASM /p
