SET BIN=..\..\bin
SET OBJ=OBJ

%BIN%\asm %OBJ%\ABS.ASM /p
%BIN%\asm %OBJ%\ATOI.ASM /p
%BIN%\asm %OBJ%\ATOIB.ASM /p
%BIN%\asm %OBJ%\AUXBUF.ASM /p
%BIN%\asm %OBJ%\AVAIL.ASM /p
%BIN%\asm %OBJ%\BSEEK.ASM /p
%BIN%\asm %OBJ%\BTELL.ASM /p
%BIN%\asm %OBJ%\CALL.ASM /p
%BIN%\asm %OBJ%\CALLOC.ASM /p
%BIN%\asm %OBJ%\CLEARERR.ASM /p
%BIN%\asm %OBJ%\CSEEK.ASM /p
%BIN%\asm %OBJ%\CSYSLIB.ASM /p
%BIN%\asm %OBJ%\CTELL.ASM /p
%BIN%\asm %OBJ%\DTOI.ASM /p
%BIN%\asm %OBJ%\EXIT.ASM /p
%BIN%\asm %OBJ%\FCLOSE.ASM /p
%BIN%\asm %OBJ%\FEOF.ASM /p
%BIN%\asm %OBJ%\FERROR.ASM /p
%BIN%\asm %OBJ%\FGETC.ASM /p
%BIN%\asm %OBJ%\FGETS.ASM /p
%BIN%\asm %OBJ%\FOPEN.ASM /p
%BIN%\asm %OBJ%\FPRINTF.ASM /p
%BIN%\asm %OBJ%\FPUTC.ASM /p
%BIN%\asm %OBJ%\FPUTS.ASM /p
%BIN%\asm %OBJ%\FREAD.ASM /p
%BIN%\asm %OBJ%\FREE.ASM /p
%BIN%\asm %OBJ%\FREOPEN.ASM /p
%BIN%\asm %OBJ%\FSCANF.ASM /p
%BIN%\asm %OBJ%\FWRITE.ASM /p
%BIN%\asm %OBJ%\GETARG.ASM /p
%BIN%\asm %OBJ%\GETCHAR.ASM /p
%BIN%\asm %OBJ%\IS.ASM /p
%BIN%\asm %OBJ%\ISASCII.ASM /p
%BIN%\asm %OBJ%\ISATTY.ASM /p
%BIN%\asm %OBJ%\ISCONS.ASM /p
%BIN%\asm %OBJ%\ITOA.ASM /p
%BIN%\asm %OBJ%\ITOAB.ASM /p
%BIN%\asm %OBJ%\ITOD.ASM /p
%BIN%\asm %OBJ%\ITOO.ASM /p
%BIN%\asm %OBJ%\ITOU.ASM /p
%BIN%\asm %OBJ%\ITOX.ASM /p
%BIN%\asm %OBJ%\LEFT.ASM /p
%BIN%\asm %OBJ%\LEXCMP.ASM /p
%BIN%\asm %OBJ%\MALLOC.ASM /p
%BIN%\asm %OBJ%\OTOI.ASM /p
%BIN%\asm %OBJ%\PAD.ASM /p
%BIN%\asm %OBJ%\POLL.ASM /p
%BIN%\asm %OBJ%\PUTCHAR.ASM /p
%BIN%\asm %OBJ%\PUTS.ASM /p
%BIN%\asm %OBJ%\RENAME.ASM /p
%BIN%\asm %OBJ%\REVERSE.ASM /p
%BIN%\asm %OBJ%\REWIND.ASM /p
%BIN%\asm %OBJ%\SIGN.ASM /p
%BIN%\asm %OBJ%\STRCAT.ASM /p
%BIN%\asm %OBJ%\STRCHR.ASM /p
%BIN%\asm %OBJ%\STRCMP.ASM /p
%BIN%\asm %OBJ%\STRCPY.ASM /p
%BIN%\asm %OBJ%\STRLEN.ASM /p
%BIN%\asm %OBJ%\STRNCAT.ASM /p
%BIN%\asm %OBJ%\STRNCMP.ASM /p
%BIN%\asm %OBJ%\STRNCPY.ASM /p
%BIN%\asm %OBJ%\STRRCHR.ASM /p
%BIN%\asm %OBJ%\TOASCII.ASM /p
%BIN%\asm %OBJ%\TOLOWER.ASM /p
%BIN%\asm %OBJ%\TOUPPER.ASM /p
%BIN%\asm %OBJ%\UNGETC.ASM /p
%BIN%\asm %OBJ%\UNLINK.ASM /p
%BIN%\asm %OBJ%\UTOI.ASM /p
%BIN%\asm %OBJ%\XTOI.ASM /p
