SET BIN=..\..\bin
SET SRC=..\src

%BIN%\CC %SRC%\ABS.C >ABS.ASM -a -p
%BIN%\CC %SRC%\ATOI.C >ATOI.ASM -a -p
%BIN%\CC %SRC%\ATOIB.C >ATOIB.ASM -a -p
%BIN%\CC %SRC%\AUXBUF.C >AUXBUF.ASM -a -p
%BIN%\CC %SRC%\AVAIL.C >AVAIL.ASM -a -p
%BIN%\CC %SRC%\BSEEK.C >BSEEK.ASM -a -p
%BIN%\CC %SRC%\BTELL.C >BTELL.ASM -a -p
COPY %SRC%\CALL.ASM CALL.ASM
%BIN%\CC %SRC%\CALLOC.C >CALLOC.ASM -a -p
%BIN%\CC %SRC%\CLEARERR.C >CLEARERR.ASM -a -p
COPY %SRC%\CLIB.H CLIB.H
%BIN%\CC %SRC%\CSEEK.C >CSEEK.ASM -a -p
%BIN%\CC %SRC%\CSYSLIB.C >CSYSLIB.ASM -a -p
%BIN%\CC %SRC%\CTELL.C >CTELL.ASM -a -p
%BIN%\CC %SRC%\DTOI.C >DTOI.ASM -a -p
%BIN%\CC %SRC%\EXIT.C >EXIT.ASM -a -p
%BIN%\CC %SRC%\FCLOSE.C >FCLOSE.ASM -a -p
%BIN%\CC %SRC%\FEOF.C >FEOF.ASM -a -p
%BIN%\CC %SRC%\FERROR.C >FERROR.ASM -a -p
%BIN%\CC %SRC%\FGETC.C >FGETC.ASM -a -p
%BIN%\CC %SRC%\FGETS.C >FGETS.ASM -a -p
%BIN%\CC %SRC%\FOPEN.C >FOPEN.ASM -a -p
%BIN%\CC %SRC%\FPRINTF.C >FPRINTF.ASM -a -p
%BIN%\CC %SRC%\FPUTC.C >FPUTC.ASM -a -p
%BIN%\CC %SRC%\FPUTS.C >FPUTS.ASM -a -p
%BIN%\CC %SRC%\FREAD.C >FREAD.ASM -a -p
%BIN%\CC %SRC%\FREE.C >FREE.ASM -a -p
%BIN%\CC %SRC%\FREOPEN.C >FREOPEN.ASM -a -p
%BIN%\CC %SRC%\FSCANF.C >FSCANF.ASM -a -p
%BIN%\CC %SRC%\FWRITE.C >FWRITE.ASM -a -p
%BIN%\CC %SRC%\GETARG.C >GETARG.ASM -a -p
%BIN%\CC %SRC%\GETCHAR.C >GETCHAR.ASM -a -p
%BIN%\CC %SRC%\IS.C >IS.ASM -a -p
%BIN%\CC %SRC%\ISASCII.C >ISASCII.ASM -a -p
%BIN%\CC %SRC%\ISATTY.C >ISATTY.ASM -a -p
%BIN%\CC %SRC%\ISCONS.C >ISCONS.ASM -a -p
%BIN%\CC %SRC%\ITOA.C >ITOA.ASM -a -p
%BIN%\CC %SRC%\ITOAB.C >ITOAB.ASM -a -p
%BIN%\CC %SRC%\ITOD.C >ITOD.ASM -a -p
%BIN%\CC %SRC%\ITOO.C >ITOO.ASM -a -p
%BIN%\CC %SRC%\ITOU.C >ITOU.ASM -a -p
%BIN%\CC %SRC%\ITOX.C >ITOX.ASM -a -p
%BIN%\CC %SRC%\LEFT.C >LEFT.ASM -a -p
%BIN%\CC %SRC%\LEXCMP.C >LEXCMP.ASM -a -p
%BIN%\CC %SRC%\MALLOC.C >MALLOC.ASM -a -p
%BIN%\CC %SRC%\OTOI.C >OTOI.ASM -a -p
%BIN%\CC %SRC%\PAD.C >PAD.ASM -a -p
%BIN%\CC %SRC%\POLL.C >POLL.ASM -a -p
%BIN%\CC %SRC%\PUTCHAR.C >PUTCHAR.ASM -a -p
%BIN%\CC %SRC%\PUTS.C >PUTS.ASM -a -p
%BIN%\CC %SRC%\RENAME.C >RENAME.ASM -a -p
%BIN%\CC %SRC%\REVERSE.C >REVERSE.ASM -a -p
%BIN%\CC %SRC%\REWIND.C >REWIND.ASM -a -p
%BIN%\CC %SRC%\SIGN.C >SIGN.ASM -a -p
COPY %SRC%\STDIO.H STDIO.H
%BIN%\CC %SRC%\STRCAT.C >STRCAT.ASM -a -p
%BIN%\CC %SRC%\STRCHR.C >STRCHR.ASM -a -p
%BIN%\CC %SRC%\STRCMP.C >STRCMP.ASM -a -p
%BIN%\CC %SRC%\STRCPY.C >STRCPY.ASM -a -p
%BIN%\CC %SRC%\STRLEN.C >STRLEN.ASM -a -p
%BIN%\CC %SRC%\STRNCAT.C >STRNCAT.ASM -a -p
%BIN%\CC %SRC%\STRNCMP.C >STRNCMP.ASM -a -p
%BIN%\CC %SRC%\STRNCPY.C >STRNCPY.ASM -a -p
%BIN%\CC %SRC%\STRRCHR.C >STRRCHR.ASM -a -p
%BIN%\CC %SRC%\TOASCII.C >TOASCII.ASM -a -p
%BIN%\CC %SRC%\TOLOWER.C >TOLOWER.ASM -a -p
%BIN%\CC %SRC%\TOUPPER.C >TOUPPER.ASM -a -p
%BIN%\CC %SRC%\UNGETC.C >UNGETC.ASM -a -p
%BIN%\CC %SRC%\UNLINK.C >UNLINK.ASM -a -p
%BIN%\CC %SRC%\UTOI.C >UTOI.ASM -a -p
%BIN%\CC %SRC%\XTOI.C >XTOI.ASM -a -p

