SET BIN=..\..\bin

%BIN%\asm ABS.ASM /p
%BIN%\asm ATOI.ASM /p
%BIN%\asm ATOIB.ASM /p
%BIN%\asm AUXBUF.ASM /p
%BIN%\asm AVAIL.ASM /p
%BIN%\asm BSEEK.ASM /p
%BIN%\asm BTELL.ASM /p
%BIN%\asm CALL.ASM /p
%BIN%\asm CALLOC.ASM /p
%BIN%\asm CLEARERR.ASM /p
%BIN%\asm CSEEK.ASM /p
%BIN%\asm CSYSLIB.ASM /p
%BIN%\asm CTELL.ASM /p
%BIN%\asm DTOI.ASM /p
%BIN%\asm EXIT.ASM /p
%BIN%\asm FCLOSE.ASM /p
%BIN%\asm FEOF.ASM /p
%BIN%\asm FERROR.ASM /p
%BIN%\asm FGETC.ASM /p
%BIN%\asm FGETS.ASM /p
%BIN%\asm FOPEN.ASM /p
%BIN%\asm FPRINTF.ASM /p
%BIN%\asm FPUTC.ASM /p
%BIN%\asm FPUTS.ASM /p
%BIN%\asm FREAD.ASM /p
%BIN%\asm FREE.ASM /p
%BIN%\asm FREOPEN.ASM /p
%BIN%\asm FSCANF.ASM /p
%BIN%\asm FWRITE.ASM /p
%BIN%\asm GETARG.ASM /p
%BIN%\asm GETCHAR.ASM /p
%BIN%\asm IS.ASM /p
%BIN%\asm ISASCII.ASM /p
%BIN%\asm ISATTY.ASM /p
%BIN%\asm ISCONS.ASM /p
%BIN%\asm ITOA.ASM /p
%BIN%\asm ITOAB.ASM /p
%BIN%\asm ITOD.ASM /p
%BIN%\asm ITOO.ASM /p
%BIN%\asm ITOU.ASM /p
%BIN%\asm ITOX.ASM /p
%BIN%\asm LEFT.ASM /p
%BIN%\asm LEXCMP.ASM /p
%BIN%\asm MALLOC.ASM /p
%BIN%\asm OTOI.ASM /p
%BIN%\asm PAD.ASM /p
%BIN%\asm POLL.ASM /p
%BIN%\asm PUTCHAR.ASM /p
%BIN%\asm PUTS.ASM /p
%BIN%\asm RENAME.ASM /p
%BIN%\asm REVERSE.ASM /p
%BIN%\asm REWIND.ASM /p
%BIN%\asm SIGN.ASM /p
%BIN%\asm STRCAT.ASM /p
%BIN%\asm STRCHR.ASM /p
%BIN%\asm STRCMP.ASM /p
%BIN%\asm STRCPY.ASM /p
%BIN%\asm STRLEN.ASM /p
%BIN%\asm STRNCAT.ASM /p
%BIN%\asm STRNCMP.ASM /p
%BIN%\asm STRNCPY.ASM /p
%BIN%\asm STRRCHR.ASM /p
%BIN%\asm TOASCII.ASM /p
%BIN%\asm TOLOWER.ASM /p
%BIN%\asm TOUPPER.ASM /p
%BIN%\asm UNGETC.ASM /p
%BIN%\asm UNLINK.ASM /p
%BIN%\asm UTOI.ASM /p
%BIN%\asm XTOI.ASM /p
