SET BIN=..\..\bin
SET SRC=..\src
SET OBJ=OBJ

MKDIR OBJ

%BIN%\CC %SRC%\ABS.C >%OBJ%\ABS.ASM -a -p
%BIN%\CC %SRC%\ATOI.C >%OBJ%\ATOI.ASM -a -p
%BIN%\CC %SRC%\ATOIB.C >%OBJ%\ATOIB.ASM -a -p
%BIN%\CC %SRC%\AUXBUF.C >%OBJ%\AUXBUF.ASM -a -p
%BIN%\CC %SRC%\AVAIL.C >%OBJ%\AVAIL.ASM -a -p
%BIN%\CC %SRC%\BSEEK.C >%OBJ%\BSEEK.ASM -a -p
%BIN%\CC %SRC%\BTELL.C >%OBJ%\BTELL.ASM -a -p
COPY %SRC%\CALL.ASM %OBJ%\CALL.ASM
%BIN%\CC %SRC%\CALLOC.C >%OBJ%\CALLOC.ASM -a -p
%BIN%\CC %SRC%\CLEARERR.C >%OBJ%\CLEARERR.ASM -a -p
%BIN%\CC %SRC%\CSEEK.C >%OBJ%\CSEEK.ASM -a -p
%BIN%\CC %SRC%\CSYSLIB.C >%OBJ%\CSYSLIB.ASM -a -p
%BIN%\CC %SRC%\CTELL.C >%OBJ%\CTELL.ASM -a -p
%BIN%\CC %SRC%\DTOI.C >%OBJ%\DTOI.ASM -a -p
%BIN%\CC %SRC%\EXIT.C >%OBJ%\EXIT.ASM -a -p
%BIN%\CC %SRC%\FCLOSE.C >%OBJ%\FCLOSE.ASM -a -p
%BIN%\CC %SRC%\FEOF.C >%OBJ%\FEOF.ASM -a -p
%BIN%\CC %SRC%\FERROR.C >%OBJ%\FERROR.ASM -a -p
%BIN%\CC %SRC%\FGETC.C >%OBJ%\FGETC.ASM -a -p
%BIN%\CC %SRC%\FGETS.C >%OBJ%\FGETS.ASM -a -p
%BIN%\CC %SRC%\FOPEN.C >%OBJ%\FOPEN.ASM -a -p
%BIN%\CC %SRC%\FPRINTF.C >%OBJ%\FPRINTF.ASM -a -p
%BIN%\CC %SRC%\FPUTC.C >%OBJ%\FPUTC.ASM -a -p
%BIN%\CC %SRC%\FPUTS.C >%OBJ%\FPUTS.ASM -a -p
%BIN%\CC %SRC%\FREAD.C >%OBJ%\FREAD.ASM -a -p
%BIN%\CC %SRC%\FREE.C >%OBJ%\FREE.ASM -a -p
%BIN%\CC %SRC%\FREOPEN.C >%OBJ%\FREOPEN.ASM -a -p
%BIN%\CC %SRC%\FSCANF.C >%OBJ%\FSCANF.ASM -a -p
%BIN%\CC %SRC%\FWRITE.C >%OBJ%\FWRITE.ASM -a -p
%BIN%\CC %SRC%\GETARG.C >%OBJ%\GETARG.ASM -a -p
%BIN%\CC %SRC%\GETCHAR.C >%OBJ%\GETCHAR.ASM -a -p
%BIN%\CC %SRC%\IS.C >%OBJ%\IS.ASM -a -p
%BIN%\CC %SRC%\ISASCII.C >%OBJ%\ISASCII.ASM -a -p
%BIN%\CC %SRC%\ISATTY.C >%OBJ%\ISATTY.ASM -a -p
%BIN%\CC %SRC%\ISCONS.C >%OBJ%\ISCONS.ASM -a -p
%BIN%\CC %SRC%\ITOA.C >%OBJ%\ITOA.ASM -a -p
%BIN%\CC %SRC%\ITOAB.C >%OBJ%\ITOAB.ASM -a -p
%BIN%\CC %SRC%\ITOD.C >%OBJ%\ITOD.ASM -a -p
%BIN%\CC %SRC%\ITOO.C >%OBJ%\ITOO.ASM -a -p
%BIN%\CC %SRC%\ITOU.C >%OBJ%\ITOU.ASM -a -p
%BIN%\CC %SRC%\ITOX.C >%OBJ%\ITOX.ASM -a -p
%BIN%\CC %SRC%\LEFT.C >%OBJ%\LEFT.ASM -a -p
%BIN%\CC %SRC%\LEXCMP.C >%OBJ%\LEXCMP.ASM -a -p
%BIN%\CC %SRC%\MALLOC.C >%OBJ%\MALLOC.ASM -a -p
%BIN%\CC %SRC%\OTOI.C >%OBJ%\OTOI.ASM -a -p
%BIN%\CC %SRC%\PAD.C >%OBJ%\PAD.ASM -a -p
%BIN%\CC %SRC%\POLL.C >%OBJ%\POLL.ASM -a -p
%BIN%\CC %SRC%\PUTCHAR.C >%OBJ%\PUTCHAR.ASM -a -p
%BIN%\CC %SRC%\PUTS.C >%OBJ%\PUTS.ASM -a -p
%BIN%\CC %SRC%\RENAME.C >%OBJ%\RENAME.ASM -a -p
%BIN%\CC %SRC%\REVERSE.C >%OBJ%\REVERSE.ASM -a -p
%BIN%\CC %SRC%\REWIND.C >%OBJ%\REWIND.ASM -a -p
%BIN%\CC %SRC%\SIGN.C >%OBJ%\SIGN.ASM -a -p
%BIN%\CC %SRC%\STRCAT.C >%OBJ%\STRCAT.ASM -a -p
%BIN%\CC %SRC%\STRCHR.C >%OBJ%\STRCHR.ASM -a -p
%BIN%\CC %SRC%\STRCMP.C >%OBJ%\STRCMP.ASM -a -p
%BIN%\CC %SRC%\STRCPY.C >%OBJ%\STRCPY.ASM -a -p
%BIN%\CC %SRC%\STRLEN.C >%OBJ%\STRLEN.ASM -a -p
%BIN%\CC %SRC%\STRNCAT.C >%OBJ%\STRNCAT.ASM -a -p
%BIN%\CC %SRC%\STRNCMP.C >%OBJ%\STRNCMP.ASM -a -p
%BIN%\CC %SRC%\STRNCPY.C >%OBJ%\STRNCPY.ASM -a -p
%BIN%\CC %SRC%\STRRCHR.C >%OBJ%\STRRCHR.ASM -a -p
%BIN%\CC %SRC%\TOASCII.C >%OBJ%\TOASCII.ASM -a -p
%BIN%\CC %SRC%\TOLOWER.C >%OBJ%\TOLOWER.ASM -a -p
%BIN%\CC %SRC%\TOUPPER.C >%OBJ%\TOUPPER.ASM -a -p
%BIN%\CC %SRC%\UNGETC.C >%OBJ%\UNGETC.ASM -a -p
%BIN%\CC %SRC%\UNLINK.C >%OBJ%\UNLINK.ASM -a -p
%BIN%\CC %SRC%\UTOI.C >%OBJ%\UTOI.ASM -a -p
%BIN%\CC %SRC%\XTOI.C >%OBJ%\XTOI.ASM -a -p

